api_key: 'key-a848f98aee71e589a108aa9e2a68bde0'
domain: 'mg.nightlyreview.org'
username: 'postmaster@mg.nightlyreview.org'
password: '0c8ae85b3fedbc05999dcd0146f69724'
nightly_admin_username: 'info@nightlyreview.org '
